name: Terraform Validation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Initialize Dev
        working-directory: environments/dev
        run: terraform init -backend=false

      - name: Validate Dev
        working-directory: environments/dev
        run: terraform validate

      - name: Initialize Staging
        working-directory: environments/staging
        run: terraform init -backend=false

      - name: Validate Staging
        working-directory: environments/staging
        run: terraform validate

      - name: Initialize Production
        working-directory: environments/prod
        run: terraform init -backend=false

      - name: Validate Production
        working-directory: environments/prod
        run: terraform validate